// NgFrontEnd/src/app/product-detail/product-detail.component.ts
import { CommonModule, NgFor, NgIf, NgSwitch, NgSwitchCase, NgSwitchDefault } from '@angular/common';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import Swal from 'sweetalert2';
import { CartService } from '../cart.service';
import { FeedbackService } from '../feedback.service';
import { OrderService } from '../order.service';
import { PaymentService } from '../payment.service';
import { ProductService } from '../product.service';
import { UserService } from '../user.service';

declare var Razorpay:any;

@Component({
  selector: 'app-product-detail',
  imports: [NgFor, NgSwitch, NgSwitchCase, NgSwitchDefault,CommonModule, NgIf, FormsModule],
  templateUrl: './product-detail.component.html',
  styleUrl: './product-detail.component.css'
})
export class ProductDetailComponent {
  product_id: any;
  productData: any = {};
  user: any = {};
  feedback: any[] = [];
  newComment: any = { rating: '', text: '' };
  quantity: number = 1;

  constructor(private _router: Router,private _activeRoute: ActivatedRoute, private _apiUser: UserService, private _apiPay: PaymentService,private _apiProduct: ProductService, private _apiCart: CartService, private _feedbackService: FeedbackService, private _orderService: OrderService) { }

  ngOnInit() {
    this.product_id = this._activeRoute.snapshot.params['id'];
    this._apiProduct.getProductById(this.product_id).subscribe((res: any) => {
      this.productData = res
    })
    this.getFeedback();
  }

  addToCart(id: any) {
    this._apiCart.insert(id, this.quantity).subscribe(res => {
      Swal.fire({
        title: 'Product Added to Cart!',
        text: 'Your item has been added successfully.',
        icon: 'success',
        toast: true,  // Makes it a toast (non-blocking popup)
        position: 'top-end',  // Positions it in the top-right corner
        showConfirmButton: false,  // Hides the confirm button
        timer: 2000,  // Auto-closes after 2 seconds
        timerProgressBar: false,  // Shows a progress bar
        background: '#f9f9f9',  // Light background
        color: '#333',  // Text color
        iconColor: '#4CAF50',  // Green icon color
        showClass: {
          popup: 'animate__animated animate__fadeInRight'  // Animation for showing
        },
        hideClass: {
          popup: 'animate__animated animate__fadeOutRight'  // Animation for hiding
        }
      });
    })
  }

  getFeedback() {
    this._feedbackService.getFeedback(this.product_id).subscribe((res: any) => {
      if (res.feedbacks) {
        this.feedback = res.feedbacks; // Store feedbacks in the array
      } else {
        this.feedback = [];
      }
    });
  }

  submitComment() {
    if (this.newComment.text && this.newComment.rating) {
      this._feedbackService.newComment(this.product_id, this.newComment).subscribe(res => {
        Swal.fire({
          title: 'Thank you for your feedback!',
          text: 'Your comment has been submitted successfully.',
          icon: 'success',
          toast: true,
          position: 'top-end',
          showConfirmButton: false,
          timer: 2000,
          background: '#f9f9f9',
          color: '#333',
          iconColor: '#4CAF50',
        });

        // Reset the new comment form
        this.newComment = { rating: '', text: '' };
        this.getFeedback(); // Reload feedback after submission
      }, error => {
        Swal.fire({
          title: 'Error',
          text: 'There was an issue submitting your comment. Please try again later.',
          icon: 'error',
          toast: true,
          position: 'top-end',
          showConfirmButton: false,
          timer: 2000,
          background: '#f9f9f9',
          color: '#333',
          iconColor: '#FF6347',
        });
      });
    }
  }
 
  orderNow(): void {
    Swal.fire({
      title: 'Enter Shipping Address',
      input: 'textarea',
      inputPlaceholder: 'Enter your shipping address here...',
      showCancelButton: true,
      confirmButtonText: 'Place order',
      cancelButtonText: 'Cancel',
      confirmButtonColor: '#007bff',
      cancelButtonColor: '#dc3545',
      background: '#f9f9f9',
      color: '#333',
    }).then((result) => {
      const shippingAddress = result.value;
  
      if (shippingAddress) {
        Swal.fire({
          title: 'Select Payment Method',
          text: 'Choose how you want to pay for your order.',
          icon: 'info',
          showCancelButton: true,
          confirmButtonText: 'Pay with Razorpay',
          cancelButtonText: 'Cash on Delivery (COD)',
          confirmButtonColor: '#007bff',  // Blue for Razorpay
          cancelButtonColor: '#28a745',  // Green for COD
        }).then((paymentResult) => {
          if (paymentResult.isConfirmed) {
            this._orderService.orderSingle(this.product_id, this.quantity, shippingAddress).subscribe((res: any) => {
              this.payWithRazorpay(res.order._id, res.order.total_amount);
            });
          } else if (paymentResult.dismiss === Swal.DismissReason.cancel) {
            this._orderService.orderSingle(this.product_id, this.quantity, shippingAddress).subscribe((res: any) => {
              this.payWithCOD(res.order._id);
            });
          }
        });
      } else {
        Swal.fire({
          title: 'Address Required!',
          text: 'Please enter a shipping address to continue.',
          icon: 'error',
          confirmButtonText: 'OK',
        });
      }
    });
  }
  
  
    payWithCOD(orderId:any){
      this._apiPay.payCOD(orderId).subscribe((res:any)=>{
        Swal.fire({
          title: 'COD Selected',
          text: 'Your order has been placed successfully. Pay upon delivery.',
          icon: 'success',
          confirmButtonText: 'OK',
          confirmButtonColor: '#4CAF50'
        }).then(() => {
          this._router.navigate(['/order-history']);
        });
      })
    }
  
    payWithRazorpay(orderId:any, orderAmount:any){
      const RazorPayOptions = {
        description: 'Sample Demo',
        currency: 'INR',
        amount: orderAmount*100,
        name: this.user.first_name,
        key: 'rzp_test_LEMyImcFyWSHFZ', // Use test key
        // image: 'https://images.unsplash.com/photo-1575936123452-b67c3203c357?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aW1hZ2V8ZW58MHx8MHx8fDA%3D',
        prefill: {
          name: this.user.first_name,
          email: this.user.email,
          phone: this.user.phone_number,
        },
        theme: {
          color: '#c9184a'
        },
        method: {  // Force enable UPI
          upi: true,
          card: true,
          netbanking: true,
          wallet: true,
        },
        handler: (res: any) => {
          this.verifyPayment(orderId, res.razorpay_payment_id);
        },
        modal: {
          ondismiss: () => {
            console.log('Payment Cancelled');
          }
        }
      };
    
      const successCallBack = (paymentId: any) => {
        console.log('Payment Success:', paymentId);
      };
    
      const failureCallBack = (error: any) => {
        console.log('Payment Failed:', error);
      };
    
      Razorpay.open(RazorPayOptions, successCallBack, failureCallBack);
    }
  
    verifyPayment(orderId: any,payment_id:any) {
      this._apiPay.payRazor(orderId, payment_id).subscribe((res: any) => {
        Swal.fire({
          title: 'Payment Successful!',
          text: 'Your order has been confirmed.',
          icon: 'success',
          confirmButtonText: 'OK',
          confirmButtonColor: '#4CAF50'
        }).then(() => {
          this._router.navigate(['/order-history']);
        });
      }, (error) => {
        Swal.fire({
          title: 'Payment Failed!',
          text: 'Something went wrong. Please try again.',
          icon: 'error',
          confirmButtonText: 'Retry'
        });
      });
    }

}

<div class="container mt-5">
    <div class="row">
        <!-- Product Images Section -->
        <div class="col-md-4">
            <div id="carouselExample" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                    <!-- Loop over product images array -->
                    <div class="carousel-item" *ngFor="let image of productData?.product?.image_url; let i = index"
                        [class.active]="i === 0">
                        <img [src]="image" class="d-block w-100" alt="Product Image">
                    </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample"
                    data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExample"
                    data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>

        <div class="col-md-6">
            <h2>{{ productData?.product?.product_name }}</h2>

            <div class="d-flex align-items-center">
                <del class="me-2">₹{{ productData?.original_price }}</del>
                <h3 class="text-primary">₹{{ productData?.final_price }}</h3>
            </div>

            <div class="d-flex align-items-center">
                <h6 class="me-2">Size:</h6>
                <h6 class="text-primary">{{ productData?.product?.size }}</h6>
            </div>

            <div class="d-flex align-items-center">
                <p class="me-2">Stock:</p>
                <p *ngIf="productData?.product?.product_stock>0" class="text-success">In Stock</p>
                <p *ngIf="productData?.product?.product_stock<=0" class="text-danger">Out of Stock</p>
            </div>

            <div class="my-3">
                <span class="rating" *ngFor="let star of [1, 2, 3, 4, 5]">
                    <ng-container [ngSwitch]="true">
                        <svg *ngSwitchCase="star <= productData?.average_rating" width="18" height="18"
                            class="text-warning">
                            <use xlink:href="#star-full"></use>
                        </svg>

                        <svg *ngSwitchCase="star - 1 < productData?.average_rating && star > productData?.average_rating"
                            width="18" height="18" class="text-warning">
                            <use xlink:href="#star-half"></use>
                        </svg>

                        <svg *ngSwitchDefault width="18" height="18" class="text-muted">
                            <use xlink:href="#star-empty"></use>
                        </svg>
                    </ng-container>
                </span>
                <span class="ms-2">({{ productData?.total_ratings }} reviews)</span>
            </div>
            <p>{{ productData?.description }}</p>

            <div class="d-flex gap-3">
                <button class="btn btn-primary" (click)="addToCart(productData?.product._id)" [disabled]="productData?.product?.product_stock <= 0">Add to Cart</button>
                <button class="btn btn-warning" (click)="orderNow()">Order Now</button>
            </div>

            <div>
                <h6 class="m-2">Description:</h6>
                <p class="ms-2">{{ productData?.product?.description }}</p>
            </div>
        </div>
    </div>

    <div class="my-5">
        <h4>Customer Feedback</h4>
        <div class="mt-4">
            <h5>Leave a Feedback</h5>
            <form (ngSubmit)="submitComment()">
                <div class="mb-3">
                    <textarea [(ngModel)]="newComment.text" name="commentText" rows="4" class="form-control"
                        placeholder="Write your feedback..." required></textarea>
                </div>
                <div class="d-flex gap-2">
                    <label htmlFor="rating" class="form-label">
                        Rating
                    </label>
                    <select [(ngModel)]="newComment.rating" name="rating" class="form-select" required>
                        <option *ngFor="let rate of [1, 2, 3, 4, 5]" [value]="rate">{{ rate }}</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-primary mt-3">Submit</button>
            </form>
        </div>
        <div class="mt-5">
            <h5>All Feedback</h5>
            <div *ngIf="feedback.length > 0">
                <div *ngFor="let feedbackItem of feedback" class="mb-4 p-3 border rounded">
                    <div class="d-flex align-items-center">
                        <img *ngIf="feedbackItem.user_id.profile_picture; else defaultImage"
                            [src]="feedbackItem.user_id.profile_picture" style="border-radius: 50%; object-fit: cover"
                            width="40" height="40">
                        <ng-template #defaultImage>
                            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor"
                                class="bi bi-person-circle" viewBox="0 0 16 16">
                                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"></path>
                                <path fill-rule="evenodd"
                                    d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1">
                                </path>
                            </svg>
                        </ng-template>
                        <div class="ms-3">
                            <h6 class="mb-1">
                                {{ feedbackItem.user_id.first_name }} {{ feedbackItem.user_id.last_name }}
                            </h6>
                            <span class="text-muted">
                                {{ feedbackItem.commented_at | date: 'dd/LL/Y' }}
                            </span>
                        </div>
                    </div>
                    <div class="my-2">
                        <span class="rating" *ngFor="let star of [1, 2, 3, 4, 5]">
                            <ng-container [ngSwitch]="true">
                                <svg *ngSwitchCase="star <= productData?.average_rating" width="18" height="18"
                                    class="text-warning">
                                    <use xlink:href="#star-full"></use>
                                </svg>

                                <svg *ngSwitchCase="star - 1 < productData?.average_rating && star > productData?.average_rating"
                                    width="18" height="18" class="text-warning">
                                    <use xlink:href="#star-half"></use>
                                </svg>

                                <svg *ngSwitchDefault width="18" height="18" class="text-muted">
                                    <use xlink:href="#star-empty"></use>
                                </svg>
                            </ng-container>
                        </span>
                    </div>
                    <p>{{ feedbackItem.comment }}</p>
                </div>
            </div>
            <div *ngIf="feedback.length === 0">
                <p>No feedback available.</p>
            </div>
        </div>
    </div>
</div>

// ReactFrontEnd/src/components/ProductDetail.jsx
import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import Swal from "sweetalert2";

function ProductDetail() {
  const productUrl = 'http://localhost:3000/product';
  const cartUrl = 'http://localhost:3000/cart';
  const feedbackUrl = 'http://localhost:3000/feedback';
  const paymentUrl = 'http://localhost:3000/payment';
  const orderUrl = 'http://localhost:3000/order';
  const token = localStorage.getItem('token');
  const [productDetail, setProductDetail] = useState({});
  const [newComment, setNewComment] = useState({});
  const [feedback, setFeedback] = useState([]);
  const { id: productId } = useParams();
  const navigate = useNavigate();
  const quantity = 1;

  useEffect(() => {
    getProduct();
    getFeedback();
  }, []);

  const getProduct = () => {
    fetch(productUrl + "/" + productId, {
      method: 'GET',
      headers: {
        "Content-Type": "application/json",
        "Authorization": "Bearer " + token
      }
    })
      .then(res => res.json())
      .then(res => setProductDetail(res));
  }

  const addToCart = async (id, quantity = 1) => {
    try {
      fetch(cartUrl, {
        method: 'POST',
        body: JSON.stringify({
          productId: id,
          quantity: quantity
        }),
        headers: {
          "Content-Type": "application/json",
          "Authorization": "Bearer " + token
        }
      })
        .then(res => res.json())
        .then(res => {
          Swal.fire({
            title: "Product Added to Cart!",
            text: "Your item has been added successfully.",
            icon: "success",
            toast: true,
            position: "top-end",
            showConfirmButton: false,
            timer: 2000,
            background: "#f9f9f9",
            color: "#333",
            iconColor: "#4CAF50",
          });
        });
    } catch (error) {
      console.error("Error adding to cart", error);
    }
  };

  const submitComment = (e) => {
    e.preventDefault();

    // Post the feedback
    fetch(feedbackUrl + "/product/" + productId, {
      method: 'POST',
      body: JSON.stringify({
        rating: newComment.rating,
        comment: newComment.text
      }),
      headers: {
        "Content-Type": "application/json",
        "Authorization": "Bearer " + token
      }
    })
      .then(res => res.json())
      .then(res => {
        // Clear the input fields after successful submission
        setNewComment({
          text: '',
          rating: ''
        });

        Swal.fire({
          title: 'Thank you for your feedback!',
          text: 'Your comment has been submitted successfully.',
          icon: 'success',
          toast: true,
          position: 'top-end',
          showConfirmButton: false,
          timer: 2000,
          background: '#f9f9f9',
          color: '#333',
          iconColor: '#4CAF50',
        });
      })
      .catch(error => {
        console.error('Error submitting comment:', error);
        Swal.fire({
          title: 'Error',
          text: 'There was an issue submitting your comment. Please try again later.',
          icon: 'error',
          toast: true,
          position: 'top-end',
          showConfirmButton: false,
          timer: 2000,
          background: '#f9f9f9',
          color: '#333',
          iconColor: '#FF6347',
        });
      });
  }

  const getFeedback = () => {
    fetch(feedbackUrl + "/product/" + productId, {
      method: 'GET',
      headers: {
        "Content-Type": "application/json",
        "Authorization": "Bearer " + token
      }
    })
    .then(res => res.json())
    .then(res => {
      if (res.feedbacks) {
        setFeedback(res.feedbacks);
      } else {
        setFeedback([]);
      }
    })
  }

      const orderNow = (e) => {
          e.preventDefault();
          Swal.fire({
            title: 'Enter Shipping Address',
            input: 'textarea',
            inputPlaceholder: 'Enter your shipping address here...',
            showCancelButton: true,
            confirmButtonText: 'Place order',
            cancelButtonText: 'Cancel',
            confirmButtonColor: '#007bff',
            cancelButtonColor: '#dc3545',
            background: '#f9f9f9',
            color: '#333',
          }).then((result) => {
            const shippingAddress = result.value;
        
            if (shippingAddress) {
              Swal.fire({
                title: 'Select Payment Method',
                text: 'Choose how you want to pay for your order.',
                icon: 'info',
                showCancelButton: true,
                confirmButtonText: 'Pay with Razorpay',
                cancelButtonText: 'Cash on Delivery (COD)',
                confirmButtonColor: '#007bff',  // Blue for Razorpay
                cancelButtonColor: '#28a745',  // Green for COD
              }).then((paymentResult) => {
                if (paymentResult.isConfirmed) {
                  fetch(orderUrl, {
                    method: 'POST',
                    body: JSON.stringify({
                        product_id: productId, 
                        quantity: quantity,
                        shipping_address: shippingAddress
                    }),
                    headers: {
                        "Content-Type": "application/json",
                        "Authorization": "Bearer " + token
                    }
                })
                .then(res => res.json())
                .then(res => {
                  payWithRazorpay(res.order._id, res.order.total_amount);
                })
                } else if (paymentResult.dismiss === Swal.DismissReason.cancel) {
                  fetch(orderUrl, {
                    method: 'POST',
                    body: JSON.stringify({
                      product_id: productId, 
                      quantity: quantity,
                      shipping_address: shippingAddress
                    }),
                    headers: {
                        "Content-Type": "application/json",
                        "Authorization": "Bearer " + token
                    }
                })
                .then(res => res.json())
                .then(res => {
                  console.log(res)
                  payWithCOD(res.order._id);
                })
                }
              });
            } else {
              Swal.fire({
                title: 'Address Required!',
                text: 'Please enter a shipping address to continue.',
                icon: 'error',
                confirmButtonText: 'OK',
              });
            }
          });
      }
  
      const payWithCOD = (orderId) => {
          fetch(paymentUrl + "/cod", {
              method: 'POST',
              body: JSON.stringify({
                  order_id: orderId
              }),
              headers: {
                  "Content-Type": "application/json",
                  "Authorization": "Bearer " + token
              }
          })
              .then(res => res.json())
              .then(res => {
                  Swal.fire({
                      title: 'COD Selected',
                      text: 'Your order has been placed successfully. Pay upon delivery.',
                      icon: 'success',
                      confirmButtonText: 'OK',
                      confirmButtonColor: '#4CAF50'
                  }).then(() => {
                      navigate('/order-history');
                  });
              })
      }
  
      const payWithRazorpay = (orderId, orderAmount) => {
          const RazorPayOptions = {
              description: 'Sample Demo',
              currency: 'INR',
              amount: orderAmount * 100,
              name: "Vintage Vastra",
              key: 'rzp_test_LEMyImcFyWSHFZ', // Use test key
              // image: 'https://images.unsplash.com/photo-1575936123452-b67c3203c357?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aW1hZ2V8ZW58MHx8MHx8fDA%3D',
              prefill: {
                  name: 'abc',
                  email: 'abc@gmail.com',
                  phone: '1234567890',
              },
              theme: {
                  color: '#c9184a'
              },
              method: {  // Force enable UPI
                  upi: true,
                  card: true,
                  netbanking: true,
                  wallet: true,
              },
              handler: (res) => {
                  verifyPayment(orderId, res.razorpay_payment_id);
              },
              modal: {
                  ondismiss: () => {
                      console.log('Payment Cancelled');
                  }
              }
          };
  
          const successCallBack = (paymentId) => {
              console.log('Payment Success:', paymentId);
          };
  
          const failureCallBack = (error) => {
              console.log('Payment Failed:', error);
          };
  
          Razorpay.open(RazorPayOptions, successCallBack, failureCallBack);
      }
  
      const verifyPayment = (orderId, payment_id) => {
          fetch(paymentUrl + "/razorpay", {
              method: 'POST',
              body: JSON.stringify({
                  order_id: orderId,
                  payment_id: payment_id
              }),
              headers: {
                  "Content-Type": "application/json",
                  "Authorization": "Bearer " + token
              }
          })
              .then(res => res.json())
              .then(res => {
                  Swal.fire({
                      title: 'Payment Successful!',
                      text: 'Your order has been confirmed.',
                      icon: 'success',
                      confirmButtonText: 'OK',
                      confirmButtonColor: '#4CAF50'
                  }).then(() => {
                      navigate('/order-history');
                  });
              }, (error) => {
                  Swal.fire({
                      title: 'Payment Failed!',
                      text: 'Something went wrong. Please try again.',
                      icon: 'error',
                      confirmButtonText: 'Retry'
                  });
              })
      }

  return (
    <div className="container mt-5">
      <div className="row">
        {/* Product Images Section */}
        <div className="col-md-4">
          <div id="carouselExample" className="carousel slide" data-bs-ride="carousel">
            <div className="carousel-inner">
              {/* Loop over product images array */}
              {productDetail?.product?.image_url?.map((image, i) => (
                <div key={i} className={`carousel-item ${i === 0 ? "active" : ""}`}>
                  <img src={image} className="d-block w-100" alt="Product Image" />
                </div>
              ))}
            </div>
            <button className="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev"
            >
              <span className="carousel-control-prev-icon" aria-hidden="true"></span>
              <span className="visually-hidden">Previous</span>
            </button>
            <button className="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next" >
              <span className="carousel-control-next-icon" aria-hidden="true"></span>
              <span className="visually-hidden">Next</span>
            </button>
          </div>
        </div>

        <div className="col-md-6">
          <h2>{productDetail?.product?.product_name}</h2>

          <div className="d-flex align-items-center">
            <del className="me-2">₹{productDetail?.original_price}</del>
            <h3 className="text-primary">₹{productDetail?.final_price}</h3>
          </div>

          <div className="d-flex align-items-center">
            <h6 className="me-2">Size:</h6>
            <h6 className="text-primary">{productDetail?.product?.size}</h6>
          </div>

          <div className="my-3">
            <span className="rating">
              {[1, 2, 3, 4, 5].map(star => {
                // Check if the star is full, half or empty based on the average rating
                if (star <= productDetail.average_rating) {
                  return (
                    <svg key={star} width="18" height="18" className="text-warning">
                      <use xlinkHref="#star-full"></use>
                    </svg>
                  );
                } else if (star - 1 < productDetail.average_rating) {
                  return (
                    <svg key={star} width="18" height="18" className="text-warning">
                      <use xlinkHref="#star-half"></use>
                    </svg>
                  );
                } else {
                  return (
                    <svg key={star} width="18" height="18" className="text-muted">
                      <use xlinkHref="#star-empty"></use>
                    </svg>
                  );
                }
              })}
            </span>
            <span className="ms-2">({productDetail?.total_ratings} reviews)</span>
          </div>
          <p>{productDetail?.description}</p>

          <div className="d-flex gap-3">
            <button className="btn btn-primary" onClick={() => addToCart(productDetail?.product?._id)}>
              Add to Cart
            </button>
            <button className="btn btn-warning" onClick={(e) => orderNow(e)}>
              Order Now
            </button>
          </div>
        </div>
      </div>

      <div className="my-5">
        <h4>Customer Feedback</h4>

        {/* Comment Box */}
        <div className="mt-4">
          <h5>Leave a Feedback</h5>
          <form>
            <div className="mb-3">
              <textarea value={newComment.text} onChange={(e) => setNewComment({ ...newComment, text: e.target.value })} name="commentText" rows="4" className="form-control"  placeholder="Write your feedback..." required/>
            </div>
            <div className="d-flex gap-2">
              <label htmlFor="rating" className="form-label">
                Rating
              </label>
              <select value={newComment.rating} onChange={(e) => setNewComment({ ...newComment, rating: e.target.value })} name="rating" className="form-select" required>
                {[1, 2, 3, 4, 5].map((rate) => (
                  <option key={rate} value={rate}>
                    {rate}
                  </option>
                ))}
              </select>
            </div>
            <button type="submit" className="btn btn-primary mt-3" onClick={(e) => submitComment(e)}>
              Submit
            </button>
          </form>
        </div>

        <div className="mt-5">
          <h5>All Feedback</h5>
          {(feedback.length > 0) ? (
            feedback.map((feedbackItem) => (
              <div key={feedbackItem._id} className="mb-4 p-3 border rounded">
                <div className="d-flex align-items-center">
                {feedbackItem.user_id.profile_picture ? <img src={feedbackItem.user_id.profile_picture} style={{ borderRadius: "50%", objectFit: "cover" }} width="40" height="40"/> : <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" className="bi bi-person-circle" viewBox="0 0 16 16">
                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"></path>
                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"></path>
                </svg>}
                <div className="ms-3">
                    <h6 className="mb-1">
                      {feedbackItem.user_id.first_name} {feedbackItem.user_id.last_name}
                    </h6>
                    <span className="text-muted">
                      {new Date(feedbackItem.commented_at).toLocaleDateString()}
                    </span>
                  </div>
                </div>
                <div className="my-2">
                <span className="rating">
              {[1, 2, 3, 4, 5].map(star => {
                // Check if the star is full, half or empty based on the average rating
                if (star <= productDetail.average_rating) {
                  return (
                    <svg key={star} width="18" height="18" className="text-warning">
                      <use xlinkHref="#star-full"></use>
                    </svg>
                  );
                } else if (star - 1 < productDetail.average_rating) {
                  return (
                    <svg key={star} width="18" height="18" className="text-warning">
                      <use xlinkHref="#star-half"></use>
                    </svg>
                  );
                } else {
                  return (
                    <svg key={star} width="18" height="18" className="text-muted">
                      <use xlinkHref="#star-empty"></use>
                    </svg>
                  );
                }
              })}
            </span>
                </div>
                <p>{feedbackItem.comment}</p>
              </div>
            ))
          ) : (
            <p>No feedback available.</p>
          )}
        </div>
      </div>
    </div>
  );
}

export default ProductDetail;
