// NgFrontEnd/src/app/wishlist/wishlist.component.ts
import { NgFor, NgIf } from '@angular/common';
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import Swal from 'sweetalert2';
import { CartService } from '../cart.service';
import { ProductService } from '../product.service';
import { WishlistService } from '../wishlist.service';

@Component({
  selector: 'app-wishlist',
  imports: [NgIf, NgFor, RouterLink],
  templateUrl: './wishlist.component.html',
  styleUrl: './wishlist.component.css'
})
export class WishlistComponent {
  constructor(private _apiWishlist: WishlistService, private _apiCart: CartService, private _apiProduct: ProductService) { }
  
  wishlistProducts: any[] = [];
  suggestProducts:any [] = [];
  quantity: number = 1;
  
  ngOnInit() {
    this.getAllWishlist();
    this.getAllProduct();
  }

  getAllWishlist(){
    this._apiWishlist.getWishlist().subscribe((res: any) => {
      this.wishlistProducts = res.products
    });
  }

  addToCart(id: any) {
    this._apiCart.insert(id, this.quantity).subscribe(res => {
      Swal.fire({
        title: 'Product Added to Cart!',
        text: 'Your item has been added successfully.',
        icon: 'success',
        toast: true,  // Makes it a toast (non-blocking popup)
        position: 'top-end',  // Positions it in the top-right corner
        showConfirmButton: false,  // Hides the confirm button
        timer: 2000,  // Auto-closes after 2 seconds
        timerProgressBar: false,  // Shows a progress bar
        background: '#f9f9f9',  // Light background
        color: '#333',  // Text color
        iconColor: '#4CAF50',  // Green icon color
        showClass: {
          popup: 'animate__animated animate__fadeInRight'  // Animation for showing
        },
        hideClass: {
          popup: 'animate__animated animate__fadeOutRight'  // Animation for hiding
        }
      });
    })
  }

  removeFromWishlist(productId:any){
    this._apiWishlist.insert(productId).subscribe((res: any) => {
      this.wishlistProducts=this.wishlistProducts.filter(item => item.product_id._id!== productId)
    });
    this.getAllProduct();
  }

  addToWishlist(id: string) {
    this._apiWishlist.insert(id).subscribe((res: any) => {
      this.getAllWishlist();
      this.getAllProduct();
    })
  }
  
  getAllProduct() {
    this._apiProduct.getAll().subscribe((res: any) => {
      if (!this.wishlistProducts.length) return;
  
      const wishlistCategoryIds = this.wishlistProducts.map((item: any) => item.product_id.category_id);
      const wishlistProductIds = this.wishlistProducts.map(item => item.product_id._id);
  
      this.suggestProducts = res
        .filter((p: any) =>
          p.product_stock > 2 &&
          p.average_rating >= 4 &&
          wishlistCategoryIds.includes(p.category_id) &&
          !wishlistProductIds.includes(p._id)
        )
        .slice(0, 3);
    }); 
  }
}

<div class="container wishlist-container">
    <div class="row">
        <div class="col-lg-8">
            <h4 class="mb-3">Your Wishlist</h4>

            <div *ngIf="wishlistProducts.length === 0" class="text-center p-5">
                <svg width="150" height="150">
                    <use xlink:href="#wishlist"></use>
                </svg>
                <h5 class="mt-3 text-muted">Your wishlist is empty!</h5>
                <p>Start adding your favorite items now.</p>
                <a href="/product" class="btn btn-primary mt-2">Go to Shop</a>
            </div>

            <div class="row wishlist-card d-flex align-items-center" *ngFor="let item of wishlistProducts">
                <div class="col-2 p-0">
                    <a [routerLink]="['/product', item.product_id._id]">
                        <img [src]="item.product_id.image_url[0]" class="wishlist-img" alt="Product Image">
                    </a>
                </div>
                <div class="col flex-grow-1 m-3">
                    <h6 class="">{{item.product_id.product_name}}</h6>
                    <div class="d-flex">
                        <p class="text-muted pe-2">₹{{ item.product_id.product_price}}</p>
                        <p *ngIf="item.product_id.product_stock>0" class="text-success">In Stock</p>
                        <p *ngIf="item.product_id.product_stock<=0" class="text-danger">Out of Stock</p>
                    </div>

                    <div class="d-flex">
                        <button class="btn btn-sm btn-primary me-2" (click)="addToCart(item.product_id._id)"
                            [disabled]="item.product_id.product_stock <= 0">Move to Cart</button>
                        <button class="btn btn-sm btn-outline-primary"
                            (click)="removeFromWishlist(item.product_id._id)">Remove</button>
                    </div>
                </div>
            </div>

        </div>
        <div class="col-lg-4">
            <h5 class="mb-3">You May Also Like</h5>

            <div class="recommended-product d-flex align-items-center mb-3" *ngFor="let item of suggestProducts">
                <img [routerLink]="['/product', item._id]" [src]="item.image_url[0]" class="me-3 rounded wishlist-img"
                    alt="Recommended Product" style="cursor: pointer;">
                <div>
                    <h6 class="mb-1">{{item.product_name}}</h6>
                    <p class="text-muted mb-1">₹{{item.final_price}}</p>
                    <button class="btn btn-sm btn-outline-primary" (click)="addToWishlist(item._id)">Add to
                        Wishlist</button>
                </div>
            </div>
        </div>
    </div>
</div>

// ReactFrontEnd/src/components/Wishlist.jsx
import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import Swal from "sweetalert2";

function Wishlist() {
    const productUrl = 'http://localhost:3000/product';
    const wishlistUrl = "http://localhost:3000/wishlist";
    const cartUrl = 'http://localhost:3000/cart';
    const token = localStorage.getItem("token");
    const [wishlist, setWishlist] = useState([]);
    const [wishlistEmpty, setWishlistEmpty] = useState(false);
    const [suggestProducts, setSuggestProducts] = useState([]);
    const navigate = useNavigate();

    useEffect(() => {
        if (!token || token === 'undefined') {
            navigate('/login');
        }
        getAllWishlistProducts();
    }, []);

    useEffect(() => {
        if (wishlist.length > 0) {
            getAllProducts();
        }
    }, [wishlist]);

    const getAllWishlistProducts = () => {
        fetch(wishlistUrl + "/products", {
            method: "GET",
            headers: {
                "Content-Type": "application/json",
                "Authorization": "Bearer " + token,
            },
        })
            .then((res) => {
                if (res.status === 404) {
                    setWishlistEmpty(true);
                    setWishlist([]);
                    return null;
                }
                return res.json();
            })
            .then((res) => {
                if (res) {
                    setWishlist(res.products);
                    setWishlistEmpty(res.products.length === 0);
                }
            })
            .catch((error) => console.error("Error fetching wishlist:", error));
    };

    const removeFromWishlist = (id) => {
        fetch(wishlistUrl, {
            method: 'POST',
            body: JSON.stringify({
                productId: id,
            }),
            headers: {
                "Content-Type": "application/json",
                "Authorization": "Bearer " + token
            }
        })
            .then(res => res.json())
            .then(() => {
                setWishlist(wishlist.filter(item => item.product_id._id !== id));
            })
            .catch((error) => console.error("Error removing from wishlist:", error));
    };

    const addToWishlist = async (id) => {
        fetch(wishlistUrl, {
            method: 'POST',
            body: JSON.stringify({
                productId: id
            }),
            headers: {
                "Content-Type": "application/json",
                "Authorization": "Bearer " + token
            }
        })
            .then(res => res.json())
            .then(res => {
                getAllWishlistProducts();
            })
            .catch((error) => console.error("Error adding to wishlist:", error));
    };

    const addToCart = async (id, quantity = 1) => {
        try {
            fetch(cartUrl, {
                method: 'POST',
                body: JSON.stringify({
                    productId: id,
                    quantity: quantity
                }),
                headers: {
                    "Content-Type": "application/json",
                    "Authorization": "Bearer " + token
                }
            })
                .then(res => res.json())
                .then(() => {
                    Swal.fire({
                        title: "Product Added to Cart!",
                        text: "Your item has been added successfully.",
                        icon: "success",
                        toast: true,
                        position: "top-end",
                        showConfirmButton: false,
                        timer: 2000,
                        background: "#f9f9f9",
                        color: "#333",
                        iconColor: "#4CAF50",
                    });
                });
        } catch (error) {
            console.error("Error adding to cart", error);
        }
    };

    const getAllProducts = () => {
        fetch(productUrl, {
            method: 'GET',
            headers: {
                "Content-Type": "application/json",
                "Authorization": "Bearer " + token
            }
        })
            .then(res => res.json())
            .then(res => {
                const wishlistCategoryIds = wishlist.map(item => item.product_id.category_id);
                const wishlistProductIds = wishlist.map(item => item.product_id._id);

                setSuggestProducts(res
                    .filter((p) =>
                        p.product_stock > 2 &&
                        p.average_rating >= 4 &&
                        wishlistCategoryIds.includes(p.category_id) &&
                        !wishlistProductIds.includes(p._id)
                    )
                    .slice(0, 3));
            })
            .catch((error) => console.error("Error fetching products:", error));
    };


    return (
        <div className="container wishlist-container">
            <div className="row">
                <div className="col-lg-8">
                    <h4 className="mb-3">Your Wishlist</h4>
                    {wishlistEmpty ? (
                        <div className="text-center p-5">
                            <svg width="150" height="150"><use xlinkHref="#wishlist"></use></svg>
                            <h5 className="mt-3 text-muted">Your wishlist is empty!</h5>
                            <p>Start adding your favorite items now.</p>
                            <Link to="/product" className="btn btn-primary mt-2">Go to Shop</Link>
                        </div>
                    ) : (
                        wishlist.map((product, index) => (
                            <div className="row wishlist-card d-flex align-items-center" key={index}>
                                <div className="col-2 p-0">
                                    <Link to={"/product/" + product.product_id._id}>
                                        <img src={product.product_id.image_url[0]} className="wishlist-img" alt="Product Image" />
                                    </Link>
                                </div>
                                <div className="col flex-grow-1 m-3">
                                    <h6 className="">{product.product_id.product_name}</h6>
                                    <div className="d-flex">
                                        <p className="text-muted pe-2">₹{product.product_id.product_price}</p>
                                        {product.product_id.product_stock > 0 ? (
                                            <p className="text-success">In Stock</p>
                                        ) : (
                                            <p className="text-danger">Out of Stock</p>
                                        )}
                                    </div>

                                    <div className="d-flex">
                                        <button
                                            className="btn btn-sm btn-primary me-2"
                                            onClick={() => addToCart(product.product_id._id)}
                                            disabled={product.product_id.product_stock <= 0} >
                                            Move to Cart
                                        </button>
                                        <button
                                            className="btn btn-sm btn-outline-primary"
                                            onClick={() => removeFromWishlist(product.product_id._id)} >
                                            Remove
                                        </button>
                                    </div>
                                </div>
                            </div>
                        ))
                    )}
                </div>
                <div className="col-lg-4">
                    <h5 className="mb-3">You May Also Like</h5>
                    {suggestProducts.map((product, index) => {
                        return (
                            <div className="recommended-product d-flex align-items-center mb-3" key={index}>
                                <Link to={"/product/" + product._id}>
                                    <img
                                        src={product.image_url[0]} className="me-3 rounded wishlist-img" alt="Recommended Product" style={{ cursor: "pointer" }} />
                                </Link>
                                <div>
                                    <h6 className="mb-1">{product.product_name}</h6>
                                    <p className="text-muted mb-1">₹{product.final_price}</p>
                                    <button className="btn btn-sm btn-outline-primary" onClick={() => addToWishlist(product._id)}>
                                        Add to Wishlist
                                    </button>
                                </div>
                            </div>
                        );
                    })}
                </div>
            </div>
        </div>
    )
}

export default Wishlist;
