// ReactFrontEnd/src/components/BestSelling.jsx
import { useEffect, useState } from "react";
import Swal from "sweetalert2";

function BestSelling() {

    const productUrl = 'http://localhost:3000/product';
    const cartUrl = 'http://localhost:3000/cart';
    const wishlistUrl = 'http://localhost:3000/wishlist';
    const token = localStorage.getItem('token')
    const [product, setProduct] = useState([]);
    const [quantities, setQuantities] = useState({});
    const [wishlistProductIds, setWishlistProductIds] = useState([]);

    useEffect(() => {
        getAllProducts();

        loadWishlist();
    }, [])

    const dateDiff = (createdAt) => {
        const now = new Date();
        const sendDate = new Date(createdAt).getTime();
        const diffDay = Math.floor((now - sendDate) / (1000 * 60 * 60 * 24));
        return diffDay;
    }

    const getAllProducts = () => {
        fetch(productUrl, {
            method: 'GET',
            headers: {
                "Content-Type": "application/json",
                "Authorization": "Bearer " + token
            }
        })
            .then(res => res.json())
            .then(res => {
                const filteredProducts = res.filter(p => dateDiff(p.created_at) <= 7 && p.average_rating >= 4.5).sort((a, b) => b.total_ratings - a.total_ratings);
                setProduct(filteredProducts);
            })
            .catch(error => console.error('Error fetching products:', error));
    }

    const loadWishlist = async () => {
        try {
            fetch(wishlistUrl + "/products", {
                method: 'GET',
                headers: {
                    "Content-Type": "application/json",
                    "Authorization": "Bearer " + token
                }
            })
                .then(res => res.json())
                .then(res => {
                    if (res.products) {
                        setWishlistProductIds(res.products.map((p) => p.product_id._id));
                    }
                })
        } catch (error) {
            console.error("Error loading wishlist", error);
        }
    };

    const isInWishlist = (id) => wishlistProductIds.includes(id);

    const addToWishlist = async (id) => {
        try {
            fetch(wishlistUrl, {
                method: 'POST',
                body: JSON.stringify({
                    productId: id
                }),
                headers: {
                    "Content-Type": "application/json",
                    "Authorization": "Bearer " + token
                }
            })
                .then(res => res.json())
                .then(res => {
                    setWishlistProductIds((prev) =>
                        res.status ? [...prev, id] : prev.filter((pid) => pid !== id)
                    );
                    Swal.fire({
                        title: res.message,
                        text: "Your wishlist has been updated successfully.",
                        icon: res.status ? "success" : "info",
                        toast: true,
                        position: "top-end",
                        showConfirmButton: false,
                        timer: 2000,
                        background: "#f9f9f9",
                        color: "#333",
                        iconColor: res.status ? "#4CAF50" : "#FFA500",
                    });
                })
            // await axios.post("/api/cart", { productId: id, quantity });

        } catch (error) {
            console.error("Error updating wishlist", error);
        }



    };

    const addToCart = async (id, quantity) => {
        try {
            fetch(cartUrl, {
                method: 'POST',
                body: JSON.stringify({
                    productId: id,
                    quantity: quantity
                }),
                headers: {
                    "Content-Type": "application/json",
                    "Authorization": "Bearer " + token
                }
            })
                .then(res => res.json())
                .then(res => {
                    Swal.fire({
                        title: "Product Added to Cart!",
                        text: "Your item has been added successfully.",
                        icon: "success",
                        toast: true,
                        position: "top-end",
                        showConfirmButton: false,
                        timer: 2000,
                        background: "#f9f9f9",
                        color: "#333",
                        iconColor: "#4CAF50",
                    });
                })
            // await axios.post("/api/cart", { productId: id, quantity });

        } catch (error) {
            console.error("Error adding to cart", error);
        }
    };


    return (

        <div className="product-grid row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-3 row-cols-xl-4 row-cols-xxl-5">
            {product.map((product, index) => (
                <div className="col" key={index}>
                    <div className="product-item">
                        <figure>
                            <a href="/" title="Product Title">
                                <img src={product.image_url[0]} alt="Product Thumbnail" className="tab-image" />
                            </a>
                        </figure>
                        <div className="d-flex flex-column text-center">
                            <h3 className="fs-6 fw-normal">{product.product_name}</h3>
                            <div>
                                <span className="rating">
                                    {[1, 2, 3, 4, 5].map(star => {
                                        // Check if the star is full, half or empty based on the average rating
                                        if (star <= product.average_rating) {
                                            return (
                                                <svg key={star} width="18" height="18" className="text-warning">
                                                    <use xlinkHref="#star-full"></use>
                                                </svg>
                                            );
                                        } else if (star - 1 < product.average_rating) {
                                            return (
                                                <svg key={star} width="18" height="18" className="text-warning">
                                                    <use xlinkHref="#star-half"></use>
                                                </svg>
                                            );
                                        } else {
                                            return (
                                                <svg key={star} width="18" height="18" className="text-muted">
                                                    <use xlinkHref="#star-empty"></use>
                                                </svg>
                                            );
                                        }
                                    })}
                                </span>
                                <span>({product.total_ratings})</span>

                            </div>
                            <div className="d-flex justify-content-center align-items-center gap-2">
                                <del>₹{product.original_price}</del>
                                <span className="text-dark fw-semibold">₹{product.final_price}</span>
                                <span className="badge border border-dark-subtle rounded-0 fw-normal px-1 fs-7 lh-1 text-body-tertiary">
                                    10% OFF
                                </span>
                            </div>
                            <div className="button-area p-3 pt-0">
                                <div className="row g-1 mt-2">
                                    <div className="col-3">
                                        <input
                                            type="number"
                                            className="form-control border-dark-subtle input-number quantity"
                                            value={quantities[product._id] || 1}
                                            onChange={(e) => setQuantities({ ...quantities, [product._id]: e.target.value })}
                                        />
                                    </div>
                                    <div className="col">
                                        <button
                                            className="btn btn-primary rounded-1 p-2 fs-7 btn-cart"
                                            onClick={() => addToCart(product._id, quantities[product._id] || 1)}>
                                            <svg width="18" height="18"><use xlinkHref="#cart"></use></svg> Add to Cart
                                        </button>
                                    </div>
                                    <div className="col-2 p-2">
                                        {isInWishlist(product._id) ? (
                                            <a className="wishlist-btn" onClick={() => addToWishlist(product._id)} style={{ cursor: "pointer" }}>
                                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="red"
                                                    class="bi bi-heart-fill" viewBox="0 0 16 16">
                                                    <path fill-rule="evenodd"
                                                        d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314">
                                                    </path>
                                                </svg>
                                            </a>
                                        ) : (
                                            <a className="wishlist-btn" onClick={() => addToWishlist(product._id)} style={{ cursor: "pointer" }}>
                                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                                                    fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                                                    <path
                                                        d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15">
                                                    </path>
                                                </svg>
                                            </a>
                                        )}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            ))}
        </div>
    );
}

export default BestSelling;

// NgFrontEnd/src/app/best-selling/best-selling.component.ts
import { NgFor, NgIf, NgSwitch, NgSwitchCase, NgSwitchDefault } from '@angular/common';
import { Component } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import Swal from 'sweetalert2';
import { CartService } from '../cart.service';
import { Product } from '../product';
import { ProductService } from '../product.service';
import { WishlistService } from '../wishlist.service';

@Component({
  selector: 'app-best-selling',
  imports: [NgFor, NgIf, NgSwitch, NgSwitchCase, NgSwitchDefault, RouterLink],
  templateUrl: './best-selling.component.html',
  styleUrl: './best-selling.component.css'
})
export class BestSellingComponent {
  products: Product[] = [];
  wishlistProductIds: string[] = [];
  quantity: number = 1;
  now:any;

  constructor(private _activeRoute: ActivatedRoute, private _apiProduct: ProductService, private _apiCart: CartService, private _apiWishlist: WishlistService) { }
  
  ngOnInit(): void {
    this.loadWishlist();
    this.getAllProduct();
  }

  
    loadWishlist() {
      this._apiWishlist.getWishlist().subscribe((res: any) => {
        if (res.products) {
          this.wishlistProductIds = res.products.map((p: any) => p.product_id._id);
        }
      });
    }
  
    addToCart(id: any) {
      this._apiCart.insert(id, this.quantity).subscribe(res => {
        Swal.fire({
          title: 'Product Added to Cart!',
          text: 'Your item has been added successfully.',
          icon: 'success',
          toast: true,  // Makes it a toast (non-blocking popup)
          position: 'top-end',  // Positions it in the top-right corner
          showConfirmButton: false,  // Hides the confirm button
          timer: 2000,  // Auto-closes after 2 seconds
          timerProgressBar: false,  // Shows a progress bar
          background: '#f9f9f9',  // Light background
          color: '#333',  // Text color
          iconColor: '#4CAF50',  // Green icon color
          showClass: {
            popup: 'animate__animated animate__fadeInRight'  // Animation for showing
          },
          hideClass: {
            popup: 'animate__animated animate__fadeOutRight'  // Animation for hiding
          }
        });
      })
    }
  
    isInWishlist(id: string): boolean {
      return this.wishlistProductIds.includes(id);
    }
  
    addToWishlist(id: string) {
      this._apiWishlist.insert(id).subscribe((res: any) => {
    
        if (res.status) {
          if (!this.isInWishlist(id)) {
            this.wishlistProductIds.push(id);
          }
        } else {
          this.wishlistProductIds = this.wishlistProductIds.filter(pid => pid !== id);
        }
    
        // Show SweetAlert with dynamic message from response
        Swal.fire({
          title: res.message,  // Show response message as title
          text: 'Your wishlist has been updated successfully.',
          icon: res.status ? 'success' : 'info',  // Success for added, Info for removed
          toast: true,
          position: 'top-end',
          showConfirmButton: false,
          timer: 2000,
          timerProgressBar: false,
          background: '#f9f9f9',
          color: '#333',
          iconColor: res.status ? '#4CAF50' : '#FFA500', // Green for success, Orange for removed
          showClass: {
            popup: 'animate__animated animate__fadeInRight'
          },
          hideClass: {
            popup: 'animate__animated animate__fadeOutRight'
          }
        });
    
      });
    }

    dateDiff(createdAt:any){
      this.now = new Date();
      const sendDate = new Date(createdAt).getTime();
      const diffDay = Math.floor((this.now - sendDate) / (1000 * 60 * 60 * 24));
      return diffDay;
  }
  
    getAllProduct() {
      this._apiProduct.getAll().subscribe((res: any) => {
        this.products = res.filter((p:any) => this.dateDiff(p.created_at) <= 7 && p.average_rating >= 4.5).sort((a:any, b:any) => b.total_ratings - a.total_ratings).slice(0, 10);
      })
    }
}

<section class="pb-5">
    <div class="container-lg">

        <div class="row">
            <div class="col-md-12">

                <div class="section-header d-flex flex-wrap justify-content-between my-4">

                    <h2 class="section-title">Best selling products</h2>

                    <div class="d-flex align-items-center">
                        <a href="#" class="btn btn-primary rounded-1">View All</a>
                    </div>
                </div>

            </div>
        </div>

        <div class="row">
            <div class="col-md-12">

                <div
                    class="product-grid row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-3 row-cols-xl-4 row-cols-xxl-5">

                    <div class="col" *ngFor="let prod of products">
                        <div class="product-item">
                            <figure>
                                <a [routerLink]="['/product', prod._id]" title="Product Title">
                                    <img src={{prod.image_url[0]}} alt="Product Thumbnail" class="tab-image">
                                </a>
                            </figure>
                            <div class="d-flex flex-column text-center">
                                <h3 class="fs-6 fw-normal">{{prod.product_name}}</h3>
                                <div>
                                    <span class="rating" *ngFor="let star of [1, 2, 3, 4, 5]">
                                        <ng-container [ngSwitch]="true">
                                          <!-- Full Star -->
                                          <svg *ngSwitchCase="star <= prod.average_rating" width="18" height="18" class="text-warning">
                                            <use xlink:href="#star-full"></use>
                                          </svg>
                                          
                                          <!-- Half Star -->
                                          <svg *ngSwitchCase="star - 1 < prod.average_rating && star > prod.average_rating" width="18" height="18" class="text-warning">
                                            <use xlink:href="#star-half"></use>
                                          </svg>
                                      
                                          <!-- Empty Star -->
                                          <svg *ngSwitchDefault width="18" height="18" class="text-muted">
                                            <use xlink:href="#star-empty"></use>
                                          </svg>
                                        </ng-container>
                                      </span>
                                      
                                    <span>({{prod.total_ratings}})</span>
                                </div>
                                <div class="d-flex justify-content-center align-items-center gap-2">
                                    <del>₹{{prod.original_price}}</del>
                                    <span class="text-dark fw-semibold">₹{{prod.final_price}}</span>
                                    <span
                                        class="badge border border-dark-subtle rounded-0 fw-normal px-1 fs-7 lh-1 text-body-tertiary">10%
                                        OFF</span>
                                </div>
                                <div class="button-area p-3 pt-0">
                                    <div class="row g-1 mt-2">
                                        <!-- <div class="col-3"><input type="number" name="quantity"
                                                class="form-control border-dark-subtle input-number quantity" value="1">
                                        </div> -->
                                        <div class="col">
                                            <button class="btn btn-primary rounded-1 p-2 fs-7 btn-cart"
                                            (click)="addToCart(prod._id)">
                                            <svg width="18" height="18">
                                                <use xlink:href="#cart"></use>
                                            </svg> Add to Cart
                                        </button>
                                        </div>
                                        <div class="col-2 p-2">
                                            <a *ngIf="isInWishlist(prod._id); else notLike" (click)="addToWishlist(prod._id)" style="cursor: pointer;">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="red"
                                                    class="bi bi-heart-fill" viewBox="0 0 16 16">
                                                    <path fill-rule="evenodd"
                                                        d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314">
                                                    </path>
                                                </svg>
                                            </a>
                                            <ng-template #notLike>
                                                <a (click)="addToWishlist(prod._id)" style="cursor: pointer;">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                                                        fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                                                        <path
                                                            d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15">
                                                        </path>
                                                    </svg>
                                                </a>
                                            </ng-template>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
                <!-- / product-grid -->


            </div>
        </div>
    </div>
</section>
