// ReactFrontEnd/src/components/Cart.jsx
import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import Swal from "sweetalert2";

function Cart() {
    const cartUrl = "http://localhost:3000/cart";
    const paymentUrl = 'http://localhost:3000/payment';
    const orderUrl = 'http://localhost:3000/order';
    const token = localStorage.getItem("token");
    const [cart, setCart] = useState([]);
    const [cartEmpty, setCartEmpty] = useState(false);
    const [showAddressForm, setShowAddressForm] = useState(false);
    const [shippingAddress, setShippingAddress] = useState('');
    const [id, setId] = useState('');
    const navigate = useNavigate();

    useEffect(() => {
        if (!token || token === 'undefined') {
            navigate('/login')
        }
        getAllCartProducts();
    }, []);

    const getAllCartProducts = () => {
        fetch(cartUrl + "/products", {
            method: "GET",
            headers: {
                "Content-Type": "application/json",
                "Authorization": "Bearer " + token,
            },
        })
            .then((res) => {
                if (res.status === 404) {
                    setCartEmpty(true); // Mark cart as empty
                    setCart([]); // Clear the cart
                    return null;
                }
                return res.json();
            })
            .then((res) => {
                if (res) {
                    setId(res._id);
                    setCart(res.products);
                    setCartEmpty(res.products.length === 0); // Handle empty array case
                }
            })
            .catch((error) => console.error("Error fetching cart:", error));
    };

    const updateCart = (productId, quantity, stock) => {
        if (quantity < 1 || quantity > 10 || quantity > stock) {
            return;
        }
        const itemIndex = cart.findIndex(item => item._id === productId);
        if (itemIndex !== -1) {
            cart[itemIndex].quantity = quantity;
        }
        try {
            fetch(cartUrl + "/" + id, {
                method: 'PATCH',
                body: JSON.stringify({
                    productId: productId,
                    quantity: quantity
                }),
                headers: {
                    "Content-Type": "application/json",
                    "Authorization": "Bearer " + token
                }
            }).then(res => res.json()).then(res => getAllCartProducts())
        } catch (error) {
            console.error("Error updating to cart", error);
        }
    }

    const removeProduct = (productId) => {
        fetch(cartUrl + "/" + id, {
            method: 'DELETE',
            body: JSON.stringify({
                productId: productId
            }),
            headers: {
                "Content-Type": "application/json",
                "Authorization": "Bearer " + token
            }
        }).then(res => res.json()).then(res => getAllCartProducts())
    }

    const toggleAddressForm = () => {
        setShowAddressForm(!showAddressForm);
    }
    
    const showPaymentOptions = (e) => {
        e.preventDefault();
        Swal.fire({
            title: 'Select Payment Method',
            text: 'Choose how you want to pay for your order.',
            icon: 'info',
            showCancelButton: true,
            confirmButtonText: 'Pay with Razorpay',
            cancelButtonText: 'Cash on Delivery (COD)',
            confirmButtonColor: '#007bff', // Blue for Razorpay
            cancelButtonColor: '#28a745', // Green for COD
            background: '#f9f9f9',
            color: '#333'
        }).then((result) => {
            if (result.isConfirmed) {
                fetch(orderUrl + "/cart", {
                    method: 'POST',
                    body: JSON.stringify({
                        shipping_address: shippingAddress
                    }),
                    headers: {
                        "Content-Type": "application/json",
                        "Authorization": "Bearer " + token
                    }
                })
                .then(res => res.json())
                .then(res => {
                    getAllCartProducts();
                    payWithRazorpay(res.order._id, res.order.total_amount);
                });
            } else if (result.dismiss === Swal.DismissReason.cancel) {
                fetch(orderUrl + "/cart", {
                    method: 'POST',
                    body: JSON.stringify({
                        shipping_address: shippingAddress
                    }),
                    headers: {
                        "Content-Type": "application/json",
                        "Authorization": "Bearer " + token
                    }
                })
                .then(res => res.json())
                .then(res => {
                    getAllCartProducts();
                    payWithCOD(res.order._id);
                });
            }
        });
    }

    const payWithCOD = (orderId) => {
        fetch(paymentUrl + "/cod", {
            method: 'POST',
            body: JSON.stringify({
                order_id: orderId
            }),
            headers: {
                "Content-Type": "application/json",
                "Authorization": "Bearer " + token
            }
        })
            .then(res => res.json())
            .then(res => {
                Swal.fire({
                    title: 'COD Selected',
                    text: 'Your order has been placed successfully. Pay upon delivery.',
                    icon: 'success',
                    confirmButtonText: 'OK',
                    confirmButtonColor: '#4CAF50'
                }).then(() => {
                    // this._router.navigate(['/order-history']); // Redirect user
                });
            })
    }

    const payWithRazorpay = (orderId, orderAmount) => {
        const RazorPayOptions = {
            description: 'Sample Demo',
            currency: 'INR',
            amount: orderAmount * 100,
            name: "Vintage Vastra",
            key: 'rzp_test_LEMyImcFyWSHFZ', // Use test key
            // image: 'https://images.unsplash.com/photo-1575936123452-b67c3203c357?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aW1hZ2V8ZW58MHx8MHx8fDA%3D',
            prefill: {
                name: 'abc',
                email: 'abc@gmail.com',
                phone: '1234567890',
            },
            theme: {
                color: '#c9184a'
            },
            method: {  // Force enable UPI
                upi: true,
                card: true,
                netbanking: true,
                wallet: true,
            },
            handler: (res) => {
                verifyPayment(orderId, res.razorpay_payment_id);
            },
            modal: {
                ondismiss: () => {
                    console.log('Payment Cancelled');
                }
            }
        };

        const successCallBack = (paymentId) => {
            console.log('Payment Success:', paymentId);
        };

        const failureCallBack = (error) => {
            console.log('Payment Failed:', error);
        };

        Razorpay.open(RazorPayOptions, successCallBack, failureCallBack);
    }

    const verifyPayment = (orderId, payment_id) => {
        fetch(paymentUrl + "/razorpay", {
            method: 'POST',
            body: JSON.stringify({
                order_id: orderId,
                payment_id: payment_id
            }),
            headers: {
                "Content-Type": "application/json",
                "Authorization": "Bearer " + token
            }
        })
            .then(res => res.json())
            .then(res => {
                Swal.fire({
                    title: 'Payment Successful!',
                    text: 'Your order has been confirmed.',
                    icon: 'success',
                    confirmButtonText: 'OK',
                    confirmButtonColor: '#4CAF50'
                }).then(() => {
                    // this._router.navigate(['/order-history']); // Redirect user
                });
            }, (error) => {
                Swal.fire({
                    title: 'Payment Failed!',
                    text: 'Something went wrong. Please try again.',
                    icon: 'error',
                    confirmButtonText: 'Retry'
                });
            })
    }

    return (
        <div className="container cart-container">
            <div className="row">
                <div className="col-lg-8">
                    <h4 className="mb-3">Shopping Cart</h4>

                    {cartEmpty ? (
                        <div className="text-center p-5">
                            <svg width="150" height="150"><use xlinkHref="#cart"></use></svg>
                            <h5 className="mt-3 text-muted">Your cart is empty!</h5>
                            <p>Looks like you haven't added anything yet.</p>
                            <Link to="/product" className="btn btn-primary mt-2">Go to Shop</Link>
                        </div>
                    ) : (
                        cart.map((product, index) => (
                            <div className="row cart-card d-flex align-items-center" key={index}>
                                <div className="col-2 p-0">
                                    <Link to={"/product/" + product.product_id._id}>
                                        <img src={product.product_id.image_url[0]} className="cart-img" alt="Product" />
                                    </Link>
                                </div>

                                <div className="col flex-grow-1">
                                    <h6 className="mb-3">{product.product_id.product_name}</h6>
                                    <div className="d-flex align-items-center">
                                        <label htmlFor="quantity" className="me-2">Qty:</label>
                                        <div className="input-group" style={{ width: "100px" }}>
                                            <button className="btn border-dark-subtle px-2" type="button" onClick={() => {
                                                updateCart(product._id, product.quantity - 1, product.product_id.product_stock);
                                            }}>
                                                <strong>-</strong>
                                            </button>

                                            <input
                                                type="text"
                                                name="quantity"
                                                className="form-control text-center border-dark-subtle"
                                                disabled
                                                value={product.quantity}
                                            />

                                            <button className="btn border-dark-subtle px-2" type="button" onClick={() => {
                                                updateCart(product._id, product.quantity + 1, product.product_id.product_stock);
                                            }}>
                                                <strong>+</strong>
                                            </button>
                                        </div>
                                        <div className="ps-3" style={{ cursor: "pointer" }} onClick={() => {
                                            removeProduct(product._id);
                                        }}>
                                            <svg width="22" height="22">
                                                <use xlinkHref="#trash"></use>
                                            </svg>
                                        </div>
                                    </div>
                                </div>

                                <div className="col-2">
                                    <strong className="text-muted">₹{product.product_id.product_price * product.quantity}</strong>
                                </div>
                            </div>
                        ))
                    )}
                </div>


                <div className="col-lg-4">
                    <h5 className="mb-3">Order Summary</h5>
                    <div className="cart-summary">
                        <p className="d-flex justify-content-between">
                            <span>Subtotal:</span>
                            <strong>₹{cart.reduce((total, p) => total + p.product_id.product_price * p.quantity, 0)}</strong>
                        </p>
                        <p className="d-flex justify-content-between">
                            <span>Total Items:</span>
                            <strong>{cart.reduce((total, p) => total + p.quantity, 0)}</strong>
                        </p>
                        <p className="d-flex justify-content-between">
                            <span>Shipping:</span>
                            <strong>Free</strong>
                        </p>
                        <hr />
                        <p className="d-flex justify-content-between">
                            <span>Total:</span>
                            <strong>₹{cart.reduce((total, p) => total + p.product_id.product_price * p.quantity, 0)}</strong>
                        </p>
                        {!showAddressForm && (
                            <button className="btn btn-primary w-100 mt-3" onClick={toggleAddressForm} >
                                Proceed to Checkout
                            </button>
                        )}

                        {showAddressForm && (
                            <form>
                                <h5 className="mt-3">Shipping Address</h5>

                                <div className="mb-2">
                                    <label htmlFor="address" className="form-label">Address</label>
                                    <textarea id="address" className="form-control" name="address" required
                                        value={shippingAddress}
                                        onChange={(e) => setShippingAddress(e.target.value)} />
                                </div>
                                <button type="submit" className="btn btn-primary w-100 mt-2" onClick={(e) => showPaymentOptions(e)}>Place Order</button>
                            </form>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
}

export default Cart;

// NgFrontEnd/src/app/cart/cart.component.ts
import { NgFor, NgIf } from '@angular/common';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import Swal from 'sweetalert2';
import { CartService } from '../cart.service';
import { OrderService } from '../order.service';
import { PaymentService } from '../payment.service';
import { UserService } from '../user.service';


declare var Razorpay:any;

@Component({
  selector: 'app-cart',
  imports: [NgFor, FormsModule, NgIf, RouterLink],
  templateUrl: './cart.component.html',
  styleUrl: './cart.component.css'
})
export class CartComponent {
  cartId = ''
  cartProduct: any[] = [];
  user: any = {};
  subtotal: number = 0;
  total: number = 0;
  totalItem: number = 0;
  showAddressForm: boolean = false;
  shippingAddress: any = ''

  constructor(private _router: Router,private _apiCart: CartService, private _apiOrder: OrderService, private _apiPay: PaymentService, private _apiUser: UserService) { }

  ngOnInit() {
    this.getAllCart();
    this.getUser();
  }

  getUser() {
    this._apiUser.getUser().subscribe((res: any) => {
      this.user = res;
    })
  }

  calculateTotal() {
    if (this.cartProduct.length > 0) {
      this.subtotal = this.cartProduct.reduce((sum, item) => {
        return sum + (item.product_id.product_price * item.quantity);
      }, 0);

      this.total = this.subtotal; // Modify if you have discounts
    } else {
      this.subtotal = 0;
      this.total = 0;
    }
  }

  getAllCart() {
    this._apiCart.getAll().subscribe((res: any) => {
      this.totalItem = res.quantity;
      this.cartProduct = res.products
      this.cartId = res._id
      this.calculateTotal();
    })
  }

  removeFromCart(productId: string) {
    this._apiCart.delete(this.cartId, productId).subscribe(
      (res: any) => {
        this.cartProduct = this.cartProduct.filter(item => item._id !== productId);
        this.totalItem = this.cartProduct.reduce((sum, item) => sum + item.quantity, 0);
        this.calculateTotal();
      },
      (err) => {
        console.error("Error removing product:", err);
      }
    );
  }

  updateCart(productId: string, quantity: number, stock: number) {
    if (quantity < 1 || quantity > 10 || quantity > stock) {
      return;
    }
    const itemIndex = this.cartProduct.findIndex(item => item._id === productId);
    if (itemIndex !== -1) {
      this.cartProduct[itemIndex].quantity = quantity;
    }

    this._apiCart.update(this.cartId, productId, quantity).subscribe((res: any) => {
      this.totalItem = this.cartProduct.reduce((sum, item) => sum + item.quantity, 0);
      this.calculateTotal();
    })
  }

  toggleAddressForm() {
    this.showAddressForm = true;
  }


  showPaymentOptions() {
    Swal.fire({
      title: 'Select Payment Method',
      text: 'Choose how you want to pay for your order.',
      icon: 'info',
      showCancelButton: true,
      confirmButtonText: 'Pay with Razorpay',
      cancelButtonText: 'Cash on Delivery (COD)',
      confirmButtonColor: '#007bff', // Blue for Razorpay
      cancelButtonColor: '#28a745', // Green for COD
      background: '#f9f9f9',
      color: '#333'
    }).then((result) => {
      if (result.isConfirmed) {
        this._apiOrder.orderFromCart(this.shippingAddress).subscribe((res: any) => {

          this.getAllCart();
          this.payWithRazorpay(res.order._id, res.order.total_amount);
        })
      } else if (result.dismiss === Swal.DismissReason.cancel) {
        this._apiOrder.orderFromCart(this.shippingAddress).subscribe((res: any) => {

          this.getAllCart();
        this.payWithCOD(res.order._id);
      })
      }
    });
  }

  payWithCOD(orderId:any){
    this._apiPay.payCOD(orderId).subscribe((res:any)=>{
      Swal.fire({
        title: 'COD Selected',
        text: 'Your order has been placed successfully. Pay upon delivery.',
        icon: 'success',
        confirmButtonText: 'OK',
        confirmButtonColor: '#4CAF50'
      }).then(() => {
        // this._router.navigate(['/order-history']); // Redirect user
      });
    })
  }

  payWithRazorpay(orderId:any, orderAmount:any){
    const RazorPayOptions = {
      description: 'Sample Demo',
      currency: 'INR',
      amount: orderAmount*100,
      name: this.user.first_name,
      key: 'rzp_test_LEMyImcFyWSHFZ', // Use test key
      // image: 'https://images.unsplash.com/photo-1575936123452-b67c3203c357?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aW1hZ2V8ZW58MHx8MHx8fDA%3D',
      prefill: {
        name: this.user.first_name,
        email: this.user.email,
        phone: this.user.phone_number,
      },
      theme: {
        color: '#c9184a'
      },
      method: {  // Force enable UPI
        upi: true,
        card: true,
        netbanking: true,
        wallet: true,
      },
      handler: (res: any) => {
        this.verifyPayment(orderId, res.razorpay_payment_id);
      },
      modal: {
        ondismiss: () => {
          console.log('Payment Cancelled');
        }
      }
    };
  
    const successCallBack = (paymentId: any) => {
      console.log('Payment Success:', paymentId);
    };
  
    const failureCallBack = (error: any) => {
      console.log('Payment Failed:', error);
    };
  
    Razorpay.open(RazorPayOptions, successCallBack, failureCallBack);
  }

  verifyPayment(orderId: any,payment_id:any) {
    this._apiPay.payRazor(orderId, payment_id).subscribe((res: any) => {
      Swal.fire({
        title: 'Payment Successful!',
        text: 'Your order has been confirmed.',
        icon: 'success',
        confirmButtonText: 'OK',
        confirmButtonColor: '#4CAF50'
      }).then(() => {
        // this._router.navigate(['/order-history']); // Redirect user
      });
    }, (error) => {
      Swal.fire({
        title: 'Payment Failed!',
        text: 'Something went wrong. Please try again.',
        icon: 'error',
        confirmButtonText: 'Retry'
      });
    });
  }
  
}

<div class="container cart-container">
    <div class="row">
        <div class="col-lg-8">
            <h4 class="mb-3">Shopping Cart</h4>

            <div *ngIf="cartProduct.length === 0" class="text-center p-5">
                <svg  width="150" height="150">
                    <use xlink:href="#cart"></use>
                </svg>
                <h5 class="mt-3 text-muted">Your cart is empty!</h5>
                <p>Looks like you haven't added anything yet.</p>
                <a routerLink="/product" class="btn btn-primary mt-2">Go to Shop</a>
            </div>

            <div class="row cart-card d-flex align-items-center" *ngFor="let item of cartProduct">
                <div class="col-2 p-0">
                    <a [routerLink]="['/product', item.product_id._id]">
                        <img [src]="item.product_id.image_url[0]" class="cart-img" alt="Product Image">
                    </a>
                </div>
                <div class="col flex-grow-1">
                    <h6 class="mb-3">{{item.product_id.product_name}}</h6>
                    <div class="d-flex align-items-center">
                        <label for="quantity" class="me-2">Qty:</label>
                        <div class="input-group" style="width: 100px;">
                            <button class="btn border-dark-subtle px-2" type="button"
                                (click)="updateCart(item._id,item.quantity-1,item.product_stock)">
                                <strong>-</strong>
                            </button>

                            <input type="text" name="quantity" [(ngModel)]="item.quantity"
                                class="form-control text-center border-dark-subtle" disabled>

                            <button class="btn border-dark-subtle px-2" type="button"
                                (click)="updateCart(item._id,item.quantity+1,item.product_stock)">
                                <strong>+</strong>
                            </button>
                        </div>
                        <div class="ps-3" (click)="removeFromCart(item._id)" style="cursor: pointer;">
                            <svg width="22" height="22">
                                <use xlink:href="#trash"></use>
                            </svg>
                        </div>
                    </div>
                </div>
                <div class="col-2">
                    <strong class="text-muted">₹{{ item.product_id.product_price * item.quantity }}</strong>
                </div>
            </div>

            <!-- <div class="cart-card d-flex align-items-center">
                <img src="" class="cart-img me-3" alt="Product Image">
                <div class="flex-grow-1">
                    <h6>Another Product</h6>
                    <p class="text-muted">₹2,999</p>
                    <div class="d-flex align-items-center">
                        <label for="quantity2" class="me-2">Qty:</label>
                        <select id="quantity2" class="form-select form-select-sm w-auto">
                            <option>1</option>
                            <option>2</option>
                            <option>3</option>
                            <option>4</option>
                        </select>
                        <button class="btn btn-link btn-remove ms-3"><i class="fas fa-trash"></i> Remove</button>
                    </div>
                </div>
            </div> -->
        </div>

        <div class="col-lg-4">
            <h5 class="mb-3">Order Summary</h5>
            <div class="cart-summary">
                <p class="d-flex justify-content-between">
                    <span>Subtotal:</span>
                    <strong>₹{{ subtotal }}</strong>
                </p>
                <p class="d-flex justify-content-between">
                    <span>Total Items:</span>
                    <strong>{{ totalItem }}</strong>
                </p>
                <p class="d-flex justify-content-between">
                    <span>Shipping:</span>
                    <strong>Free</strong>
                </p>
                <hr>
                <p class="d-flex justify-content-between">
                    <span>Total:</span>
                    <strong>₹{{ total }}</strong>
                </p>
                <button *ngIf="!showAddressForm" class="btn btn-primary w-100 mt-3" (click)="toggleAddressForm()">
                    Proceed to Checkout
                </button>

                <form *ngIf="showAddressForm" (ngSubmit)="showPaymentOptions()">
                    <h5 class="mt-3">Shipping Address</h5>

                    <div class="mb-2">
                        <label for="address" class="form-label">Address</label>
                        <textarea id="address" class="form-control" [(ngModel)]="shippingAddress" name="address" required></textarea>
                    </div>

                    <button type="submit" class="btn btn-primary w-100 mt-2">Place Order</button>
                </form>
            </div>
        </div>

    </div>
</div>
